[package]
name = "adventofcode2019"
version = "0.1.0"
authors = ["Warren Jones <warren@pencethren.org>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3" }
itertools = { version = "0.9.0" }

[dev-dependencies]
gag = { version = "0.1.10" }
serial_test = { version = "0.3.2" }

